apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frame-storage-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ index .Values "blender-worker" "frameStorage" }}
